//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PokeridosService
{
    using System;
    using System.Collections.Generic;
    
    public partial class BlindLevel
    {
        public BlindLevel()
        {
            this.AnteAmount = 0;
        }
    
        public int Id { get; set; }
        public int PeriodInMinutes { get; set; }
        public int Amount { get; set; }
        public int AnteAmount { get; set; }
        public int Order { get; set; }
    }
}
