//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PokeridosService
{
    using System;
    using System.Collections.Generic;
    
    public partial class GamePlayer
    {
        public int Id { get; set; }
        public Nullable<int> RebuyRoundIndex { get; set; }
        public Nullable<int> LostRoundIndex { get; set; }
        public int FinalPosition { get; set; }
        public int PlayerId { get; set; }
        public int GameId { get; set; }
        public int Winnings { get; set; }
    
        public virtual Player Player { get; set; }
    }
}
