//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PokeridosService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game
    {
        public Game()
        {
            this.Players = new HashSet<GamePlayer>();
        }
    
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public int TournamentId { get; set; }
    
        public virtual Tournament Tournament { get; set; }
        public virtual ICollection<GamePlayer> Players { get; set; }
    }
}
