//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations.Schema;

namespace PokeridosService
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    
    public partial class Player
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string PictureName { get; set; }

        [IgnoreDataMember]
        public string Password { get; set; }
    }
}
